# Generated by Django 4.2.2 on 2023-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
