# Generated by Django 4.2.2 on 2023-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0003_remove_cash_category_cash_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='stat',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cash',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
