# Generated by Django 4.2.2 on 2023-06-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_cash_stat_alter_cash_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='stat',
            field=models.BooleanField(default=False),
        ),
    ]
